Fix missing emit for predicates on Lambda params
Also adds tests around refinement body scoping.

Without emit_annotation_predicates for Lambda param annotations, param
annotations with refinements generate errors like the following:

```
error: type inference: Unresolved inference variable 25 in expression: __elem >= x
error: type inference: Unresolved inference variable 23 in expression: __elem
error: type inference: Unresolved inference variable 24 in expression: x
```